library(Rtsne)
library(dplyr)
library(ggplot2)
library(reshape)

## WARNING: This script performs a lot of computations, it would be best if run on a supercomputer.

# Set the number of times to run each permutation
iteration_c <- 10000

## Import the data
## This file must be generated by "Format_evidence_subtype.R" first.
rtsne_euclid <- read.table("./Data/rtsne_mut_more_germ.txt", sep="\t", header=TRUE)
rtsne_euclid <- as.data.frame(rtsne_euclid)

rtsne_euclid_g <- read.table("./Data/rtsne_evidence_more_germ.txt", sep="\t", header=TRUE)
rtsne_euclid_g <- as.data.frame(rtsne_euclid_g)

ev_sample_IDs <- rtsne_euclid[,1]

## Define function to calculate Euclidean distance

euclidean_dist <- function(x1, x2, y1, y2)
{
  return(sqrt((x1-y1)^2 + (x2-y2)^2))
}

## Define funciton to calculate distance for a series of points in the DF passed to it

euclid_calc <- function(calc_DF, cat_1, cat_2, name_1, name_2)
{
  filtered_df1 <- filter(calc_DF, calc_DF[[cat_1]]==name_1)
  filtered_df2 <- filter(calc_DF, calc_DF[[cat_2]]==name_2)

  df_1_names <- as.vector(unique(filtered_df1[,1]))
  df_2_names <- as.vector(unique(filtered_df2[,1]))
  dist_DF <- NULL

  if(nrow(filtered_df1) > 0 && nrow(filtered_df2) > 0)
  {
   for (sample_1 in df_1_names)
   {
     for(sample_2 in df_2_names)
     {
       if (sample_1 != sample_2)
       {
         select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_1)
         select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_2)
         select_2 <- head(select_2,1)
         select_1 <- head(select_1,1)
         dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) ) 
       }
     }
   }
  }
  return(dist_DF)
}

## This function looks weird, but when calling it, the groups you want to pair together
##   should be name_1 + name_3, and name_2 + name_4. Should be in order like this:
##   (df, cat_1, cat_2, BRCA1, BRCA2, Met1, Met2)

euclid_calc_2 <- function(calc_DF, cat_1, cat_2, name_1, name_2, name_3, name_4, name_5, name_6)
{
  filtered_df1 <- filter(calc_DF, calc_DF[[cat_1]]==name_1)
  filtered_df2 <- filter(calc_DF, calc_DF[[cat_1]]==name_2)
  filtered_df3 <- filter(calc_DF, calc_DF[[cat_1]]==name_3)
  filtered_df4 <- filter(calc_DF, calc_DF[[cat_1]]==name_4)
  filtered_df5 <- filter(calc_DF, calc_DF[[cat_2]]==name_5)
  filtered_df6 <- filter(calc_DF, calc_DF[[cat_2]]==name_6)

  filtered_df1 <- rbind(filtered_df1, filtered_df2, filtered_df3, filtered_df4)
  filtered_df5 <- rbind(filtered_df5, filtered_df6)

  df_1_names <- as.vector(unique(filtered_df1[,1]))
  df_2_names <- as.vector(unique(filtered_df5[,1]))
  dist_DF <- NULL

  for (sample_1 in df_1_names)
  {
    for(sample_2 in df_2_names)
    {   
      if (sample_1 != sample_2)
      {   
        select_1 <- filter(calc_DF, Sample_ID==sample_1)# , calc_DF[[cat_1]]==name_1)
        select_2 <- filter(calc_DF, Sample_ID==sample_2)# , calc_DF[[cat_2]]==name_2)
        select_2 <- head(select_2,1)
        select_1 <- head(select_1,1)  
        dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) ) 
      }   
    }   
  }

  return(dist_DF)
}

BRCA_both <- c("BRCA1", "BRCA2")
grm_both <- c("Germline_BRCA1_mutation", "Germline_BRCA2_mutation")
met_both <- c("M1", "M2")
cnv_both <- c("D1", "D2")
som_both <- c("S1", "S2")

## Create a function to create a "copy" of rtsne_euclid and randomize BRCA1/2 status
## Make sure to use set.seed() before running this function
## Also make sure to change the category being randomized if you're randomizing something different

rtsne_randomized <- rtsne_euclid
counter <- (1:nrow(rtsne_euclid))

randomize_df <- function(rand_df) {
  rand_df$BRCA_evidence <- sample(rand_df$BRCA_evidence) 
  rand_df$Met <- sample(rand_df$Met)
  rand_df$CNV <- sample(rand_df$CNV)
  rand_df$Som <- sample(rand_df$Som)
  rand_df$Aberration <- sample(rand_df$Aberration)
  rand_df$B1A <- sample(rand_df$B1A)
  rand_df$B2A <- sample(rand_df$B2A)
  rand_df$AnyBRCA1 <- sample(rand_df$AnyBRCA1)
  rand_df$AnyBRCA2 <- sample(rand_df$AnyBRCA2)
  rand_df$Ab_ger_met <- sample(rand_df$Ab_ger_met)
  rand_df$DelSom <- sample(rand_df$DelSom)
  rand_df$Other_g_mutation <- sample(rand_df$Other_g_mutation)
  return(rand_df)
}

## Calculate mean/median euclidean distances for the randomized distribution.

r_count <- (1:10)
rtsne_randomized <- rtsne_euclid

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
stat_BRCA_extra <- NULL

distribution_test <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc(rtsne_randomized, cat_1, cat_2, name_1, name_2)
    calc_2_2 <- euclid_calc(rtsne_randomized, cat_1, cat_2, name_1, name_3)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
  }
}

## For the 1_1, 1_2, and 2_2 comparisons

distribution_test_3 <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc(rtsne_randomized, cat_1, cat_1, name_1, name_2)
    calc_2_2 <- euclid_calc(rtsne_randomized, cat_2, cat_2, name_1, name_2)
    calc_1_2 <- euclid_calc(rtsne_randomized, cat_1, cat_2, name_1, name_2)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    if(!is.null(calc_1_2)) { stat_1_2 <- c(mean(calc_1_2), median(calc_1_2)) } else {stat_1_2 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
    stat_BRCA_som <<- rbind(stat_BRCA_som, stat_1_2)
  }
}

distribution_test_2 <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4, name_5, name_6, name_7, name_8){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc_2(rtsne_randomized, cat_1, cat_2, name_1, name_2, name_3, name_4, name_5, name_5)
    calc_2_2 <- euclid_calc_2(rtsne_randomized, cat_1, cat_2, name_1, name_2, name_3, name_4, name_6, name_6)
    calc_1_2 <- euclid_calc_2(rtsne_randomized, cat_1, cat_2, name_1, name_2, name_3, name_4, name_5, name_6)
    calc_4 <- euclid_calc_2(rtsne_randomized, cat_1, cat_2, name_1, name_1, name_1, name_1, name_5, name_6)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    if(!is.null(calc_1_2)) { stat_1_2 <- c(mean(calc_1_2), median(calc_1_2)) } else {stat_1_2 <- c("NA", "NA")}
    if(!is.null(calc_4)) { stat_4 <- c(mean(calc_4), median(calc_4)) } else {stat_4 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
    stat_BRCA_som <<- rbind(stat_BRCA_som, stat_1_2)
    stat_BRCA_extra <<- rbind(stat_BRCA_extra, stat_4)
  }
}

sig_pal_1 <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Other_g_mutation", "Germline_BRCA1_mutation", "PALB2")
sig_pal_2 <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Other_g_mutation", "Germline_BRCA2_mutation", "PALB2")

sig_pal_test <- euclid_calc_2(rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "PALB2", "PALB2", "PALB2", "PALB2", "Germline_BRCA2_mutation", "Germline_BRCA2_mutation")

sig_pal_1_2 <- euclid_calc_2(rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "PALB2", "PALB2", "PALB2", "PALB2", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation")
sig_pal_plus_1 <- euclid_calc_2(rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA1_mutation")
sig_pal_plus_2 <- euclid_calc_2(rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA2_mutation", "Germline_BRCA2_mutation")
sig_pal_plus_1_2 <- euclid_calc_2(rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation")

gen_pal_1 <- euclid_calc(rtsne_euclid_g, "BRCA_evidence", "Other_g_mutation", "Germline_BRCA1_mutation", "PALB2")
gen_pal_2 <- euclid_calc(rtsne_euclid_g, "BRCA_evidence", "Other_g_mutation", "Germline_BRCA2_mutation", "PALB2")
gen_pal_1_2 <- euclid_calc_2(rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "PALB2", "PALB2", "PALB2", "PALB2", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation")
gen_pal_plus_1 <- euclid_calc_2(rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA1_mutation")
gen_pal_plus_2 <- euclid_calc_2(rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA2_mutation", "Germline_BRCA2_mutation")
gen_pal_plus_1_2 <- euclid_calc_2(rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation")

med_container <- NULL

tc <- c("Sig_palb2_brca1", mean(sig_pal_1), median(sig_pal_1))
med_container <- rbind(med_container, tc)
tc <- c("Sig_palb2_brca2", mean(sig_pal_2), median(sig_pal_2))
med_container <- rbind(med_container, tc)
tc <- c("Sig_palb2_test", mean(sig_pal_test), median(sig_pal_test))
med_container <- rbind(med_container, tc)  
tc <- c("Sig_palb2_brca1&2", mean(sig_pal_1_2), median(sig_pal_1_2))
med_container <- rbind(med_container, tc) 

tc <- c("Sig_palplus_brca1", mean(sig_pal_plus_1), median(sig_pal_plus_1))
med_container <- rbind(med_container, tc)
tc <- c("Sig_palplus_brca2", mean(sig_pal_plus_2), median(sig_pal_plus_2))
med_container <- rbind(med_container, tc) 
tc <- c("Sig_palplus_brca1&2", mean(sig_pal_plus_1_2), median(sig_pal_plus_1_2))
med_container <- rbind(med_container, tc) 

tc <- c("Gen_palb2_brca1", mean(gen_pal_1), median(gen_pal_1))
med_container <- rbind(med_container, tc)
tc <- c("Gen_palb2_brca2", mean(gen_pal_2), median(gen_pal_2))
med_container <- rbind(med_container, tc) 
tc <- c("Gen_palb2_brca1&2", mean(gen_pal_1_2), median(gen_pal_1_2))
med_container <- rbind(med_container, tc) 

tc <- c("Gen_palplus_brca1", mean(gen_pal_plus_1), median(gen_pal_plus_1))
med_container <- rbind(med_container, tc)
tc <- c("Gen_palplus_brca2", mean(gen_pal_plus_2), median(gen_pal_plus_2))
med_container <- rbind(med_container, tc)
tc <- c("Gen_palplus_brca1&2", mean(gen_pal_plus_1_2), median(gen_pal_plus_1_2))
med_container <- rbind(med_container, tc)


colnames(med_container) <- c("Data_ID", "Mean", "Median")
write.table(med_container, file="./Data/sig_palb2_medians.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

set.seed(0)

print("Beginning run 1...")

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
stat_BRCA_extra <- NULL
distribution_test(iteration_c, rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "BRCA_evidence", "BRCA_evidence", "PALB2", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "Germline_BRCA1_mutation")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_palb2_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_palb2_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

print("Beginning next run...")

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
stat_BRCA_extra <- NULL
distribution_test(iteration_c, rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "BRCA_evidence", "BRCA_evidence", "PALB2", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "Germline_BRCA1_mutation")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_gen_palb2_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_gen_palb2_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
stat_BRCA_extra <- NULL
distribution_test_2(iteration_c, rtsne_euclid, "Other_g_mutation", "BRCA_evidence", "BRCA_evidence", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "Y", "Y")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
colnames(stat_BRCA_extra) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_palplus_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_palplus_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig_palplus_1_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_extra, file="./Data/Rando_sig_palb2_med_1_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
stat_BRCA_extra <- NULL
distribution_test_2(iteration_c, rtsne_euclid_g, "Other_g_mutation", "BRCA_evidence", "BRCA_evidence", "BRCA_evidence", "PALB2", "BARD1", "RAD51B", "RAD51C", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "Y", "Y")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
colnames(stat_BRCA_extra) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_gen_palplus_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_gen_palplus_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_gen_palplus_1_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_extra, file="./Data/Rando_gen_palb2_med_1_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

