library(Rtsne)
library(dplyr)
library(ggplot2)
library(reshape)

## WARNING: This script performs a lot of computations, it would be best if run on a supercomputer.

# Set the number of times to run each permutation
iteration_c <- 100

## Import the data
## This file must be generated by "Format_evidence_subtype.R" first.
rtsne_euclid <- read.table("./Data/rtsne_mut_like.txt", sep="\t", header=TRUE)
rtsne_euclid <- as.data.frame(rtsne_euclid)

rtsne_sig3 <- filter(rtsne_euclid, rtsne_euclid$Max_signature=="Signature.3")
rtsne_sig2 <- filter(rtsne_euclid, rtsne_euclid$Max_signature=="Signature.2")

ev_sample_IDs <- rtsne_euclid[,1]

## Define function to calculate Euclidean distance

euclidean_dist <- function(x1, x2, y1, y2)
{
  return(sqrt((x1-y1)^2 + (x2-y2)^2))
}

## Define funciton to calculate distance for a series of points in the DF passed to it

euclid_calc <- function(calc_DF, cat_1, cat_2, name_1, name_2)
{
  filtered_df1 <- filter(calc_DF, calc_DF[[cat_1]]==name_1)
  filtered_df2 <- filter(calc_DF, calc_DF[[cat_2]]==name_2)

  df_1_names <- as.vector(unique(filtered_df1[,1]))
  df_2_names <- as.vector(unique(filtered_df2[,1]))
  dist_DF <- NULL

  if(nrow(filtered_df1) > 0 && nrow(filtered_df2) > 0)
  {
   for (sample_1 in df_1_names)
   {
     for(sample_2 in df_2_names)
     {
       if (sample_1 != sample_2)
       {
         select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_1)
         select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_2)
         select_2 <- head(select_2,1)
         select_1 <- head(select_1,1)

         dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) ) 
       }
     }
   }
  }
  return(dist_DF)
}

## This function looks weird, but when calling it, the groups you want to pair together
##   should be name_1 + name_3, and name_2 + name_4. Should be in order like this:
##   (df, cat_1, cat_2, BRCA1, BRCA2, Met1, Met2)

euclid_calc_2 <- function(calc_DF, cat_1, cat_2, name_1, name_3, name_2, name_4)
{
  filtered_df1 <- filter(calc_DF, calc_DF[[cat_1]]==name_1)
  filtered_df2 <- filter(calc_DF, calc_DF[[cat_2]]==name_2)
  filtered_df3 <- filter(calc_DF, calc_DF[[cat_1]]==name_3)
  filtered_df4 <- filter(calc_DF, calc_DF[[cat_2]]==name_4)
  df_1_names <- as.vector(unique(filtered_df1[,1]))
  df_2_names <- as.vector(unique(filtered_df2[,1]))
  df_3_names <- as.vector(unique(filtered_df3[,1]))
  df_4_names <- as.vector(unique(filtered_df4[,1]))
  dist_DF <- NULL

  for (sample_1 in df_1_names)
  {
    for(sample_2 in df_2_names)
    {   
      if (sample_1 != sample_2)
      {   
        select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_1)
        select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_2)
        select_2 <- head(select_2,1)
        select_1 <- head(select_1,1)  
        dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) ) 
      }   
    }   
  }
  for (sample_1 in df_1_names)
  {    
    for(sample_2 in df_4_names)
    {   
      if (sample_1 != sample_2)
      {   
        select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_1)
        select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_4)
        select_2 <- head(select_2,1)
        select_1 <- head(select_1,1)
        dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) )
      }   
    }   
  }
  for (sample_1 in df_3_names)
  {    
    for(sample_2 in df_2_names)
    {   
      if (sample_1 != sample_2)
      {   
        select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_3)
        select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_2)
        select_2 <- head(select_2,1)
        select_1 <- head(select_1,1)
        dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) )
      }   
    }   
  }
  for (sample_1 in df_3_names)
  {    
    for(sample_2 in df_4_names)
    {   
      if (sample_1 != sample_2)
      {   
        select_1 <- filter(calc_DF, Sample_ID==sample_1 , calc_DF[[cat_1]]==name_3)
        select_2 <- filter(calc_DF, Sample_ID==sample_2 , calc_DF[[cat_2]]==name_4)
        select_2 <- head(select_2,1)
        select_1 <- head(select_1,1)
        dist_DF <- rbind(dist_DF, euclidean_dist( as.numeric(select_1["Val_1"]), as.numeric(select_1["Val_2"]), as.numeric(select_2["Val_1"]), as.numeric(select_2["Val_2"]) ) )
      }   
    }   
  }   
  return(dist_DF)
}

## Run the above function on the standard data set to get mean/median for BRCA 1-1, 2-2, 1-2 comparisons. 

## Create a function to create a "copy" of rtsne_euclid and randomize BRCA1/2 status

rtsne_randomized <- rtsne_euclid
counter <- (1:nrow(rtsne_euclid))

randomize_df <- function(rand_df) {
  rand_df$BRCA_evidence <- sample(rand_df$BRCA_evidence) 
  rand_df$Met <- sample(rand_df$Met)
  rand_df$CNV <- sample(rand_df$CNV)
  rand_df$Som <- sample(rand_df$Som)
  rand_df$Aberration <- sample(rand_df$Aberration)
  rand_df$B1A <- sample(rand_df$B1A)
  rand_df$B2A <- sample(rand_df$B2A)
  rand_df$AnyBRCA1 <- sample(rand_df$AnyBRCA1)
  rand_df$AnyBRCA2 <- sample(rand_df$AnyBRCA2)
  rand_df$Ab_ger_met <- sample(rand_df$Ab_ger_met)
  rand_df$DelSom <- sample(rand_df$DelSom)
  rand_df$BRCA_like <- sample(rand_df$BRCA_like)
  return(rand_df)
}

## Calculate mean/median euclidean distances for the randomized distribution.

r_count <- (1:10)
rtsne_randomized <- rtsne_euclid

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL

distribution_test <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc(rtsne_randomized, cat_1, cat_2, name_1, name_2)
    calc_2_2 <- euclid_calc(rtsne_randomized, cat_1, cat_3, name_1, name_3)
    calc_1_2 <- euclid_calc(rtsne_randomized, cat_1, cat_4, name_1, name_4)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    if(!is.null(calc_1_2)) { stat_1_2 <- c(mean(calc_1_2), median(calc_1_2)) } else {stat_1_2 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
    stat_BRCA_som <<- rbind(stat_BRCA_som, stat_1_2)
  }
}

## For the 1_1, 1_2, and 2_2 comparisons

distribution_test_3 <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc(rtsne_randomized, cat_1, cat_1, name_1, name_2)
    calc_2_2 <- euclid_calc(rtsne_randomized, cat_2, cat_2, name_1, name_2)
    calc_1_2 <- euclid_calc(rtsne_randomized, cat_1, cat_2, name_1, name_2)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    if(!is.null(calc_1_2)) { stat_1_2 <- c(mean(calc_1_2), median(calc_1_2)) } else {stat_1_2 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
    stat_BRCA_som <<- rbind(stat_BRCA_som, stat_1_2)
  }
}

distribution_test_2 <- function(iterations, rand_df, cat_1, cat_2, cat_3, cat_4, name_1, name_2, name_3, name_4, name_5, name_6, name_7, name_8){
  aggregate_stats <- NULL
  r_count <- (1:iterations)
  for (i in r_count)
  {
    rtsne_randomized <- randomize_df(rand_df)
    calc_1_1 <- euclid_calc_2(rtsne_randomized, cat_1, cat_2, name_1, name_2, name_3, name_4)
    calc_2_2 <- euclid_calc_2(rtsne_randomized, cat_1, cat_3, name_1, name_2, name_5, name_6)
    calc_1_2 <- euclid_calc_2(rtsne_randomized, cat_1, cat_4, name_1, name_2, name_7, name_8)
    if(!is.null(calc_1_1)) { stat_1_1 <- c(mean(calc_1_1), median(calc_1_1)) } else {stat_1_1 <- c("NA", "NA")}
    if(!is.null(calc_2_2)) { stat_2_2 <- c(mean(calc_2_2), median(calc_2_2)) } else {stat_2_2 <- c("NA", "NA")}
    if(!is.null(calc_1_2)) { stat_1_2 <- c(mean(calc_1_2), median(calc_1_2)) } else {stat_1_2 <- c("NA", "NA")}
    stat_BRCA_met <<- rbind(stat_BRCA_met, stat_1_1)
    stat_BRCA_cnv <<- rbind(stat_BRCA_cnv, stat_2_2)
    stat_BRCA_som <<- rbind(stat_BRCA_som, stat_1_2)
  }
}

BRCA_1_met <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "M1") 
BRCA_1_cnv <- euclid_calc(rtsne_euclid, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "D1") 
BRCA_1_som <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "S1")

BRCA_2_met <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Met", "Germline_BRCA2_mutation", "M1")
BRCA_2_cnv <- euclid_calc(rtsne_euclid, "BRCA_evidence", "CNV", "Germline_BRCA2_mutation", "D1")
BRCA_2_som <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Som", "Germline_BRCA2_mutation", "S1")

sig3_1_met <- euclid_calc(rtsne_sig3, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "M1")
sig3_1_cnv <- euclid_calc(rtsne_sig3, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "D1")
sig3_1_som <- euclid_calc(rtsne_sig3, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "S1")

sig2_1_met <- euclid_calc(rtsne_sig2, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "M1")
sig2_1_cnv <- euclid_calc(rtsne_sig2, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "D1")
sig2_1_som <- euclid_calc(rtsne_sig2, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "S1")

sig3_2_met <- euclid_calc(rtsne_sig3, "BRCA_evidence", "Met", "Germline_BRCA2_mutation", "M2")
sig3_2_cnv <- euclid_calc(rtsne_sig3, "BRCA_evidence", "CNV", "Germline_BRCA2_mutation", "D2")
sig3_2_som <- euclid_calc(rtsne_sig3, "BRCA_evidence", "Som", "Germline_BRCA2_mutation", "S2")

sig2_2_met <- euclid_calc(rtsne_sig2, "BRCA_evidence", "Met", "Germline_BRCA2_mutation", "M2")
sig2_2_cnv <- euclid_calc(rtsne_sig2, "BRCA_evidence", "CNV", "Germline_BRCA2_mutation", "D2")
sig2_2_som <- euclid_calc(rtsne_sig2, "BRCA_evidence", "Som", "Germline_BRCA2_mutation", "S2")

sigA_1_met <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "M1")
sigA_1_cnv <- euclid_calc(rtsne_euclid, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "D1")
sigA_1_som <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "S1")

sigA_2_met <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Met", "Germline_BRCA2_mutation", "M2")
sigA_2_cnv <- euclid_calc(rtsne_euclid, "BRCA_evidence", "CNV", "Germline_BRCA2_mutation", "D2")
sigA_2_som <- euclid_calc(rtsne_euclid, "BRCA_evidence", "Som", "Germline_BRCA2_mutation", "S2")

sigA_1_1 <- euclid_calc(rtsne_euclid, "B1A", "B1A", "G", "G")
sigA_2_2 <- euclid_calc(rtsne_euclid, "B2A", "B2A", "G", "G")
sigA_1_2 <- euclid_calc(rtsne_euclid, "B1A", "B2A", "G", "G")


sigA_combo_met <- euclid_calc_2(rtsne_euclid, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2")
sig2_combo_met <- euclid_calc_2(rtsne_sig2, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2")
sig3_combo_met <- euclid_calc_2(rtsne_sig3, "BRCA_evidence", "Met", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2")

sigA_combo_cnv <- euclid_calc_2(rtsne_euclid, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "D1", "D2")
sig2_combo_cnv <- euclid_calc_2(rtsne_sig2, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "D1", "D2")
sig3_combo_cnv <- euclid_calc_2(rtsne_sig3, "BRCA_evidence", "CNV", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "D1", "D2")

sigA_combo_som <- euclid_calc_2(rtsne_euclid, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "S1", "S2")
sig2_combo_som <- euclid_calc_2(rtsne_sig2, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "S1", "S2")
sig3_combo_som <- euclid_calc_2(rtsne_sig3, "BRCA_evidence", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "S1", "S2")

sigA_germ_to_all <- euclid_calc_2(rtsne_euclid, "BRCA_evidence", "Aberration", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2")
sig2_germ_to_all <- euclid_calc_2(rtsne_sig2, "BRCA_evidence", "Aberration", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2")
sig3_germ_to_all <- euclid_calc_2(rtsne_sig3, "BRCA_evidence", "Aberration", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2")

sig_brca_like <- euclid_calc(rtsne_euclid, "BRCA_like", "BRCA_like", "BRCA", "BRCA_like")
sig_brca_other <- euclid_calc(rtsne_euclid, "BRCA_like", "BRCA_like", "BRCA", "Other")
sig_like_other <- euclid_calc(rtsne_euclid, "BRCA_like", "BRCA_like", "BRCA_like", "Other")

med_container <- NULL
tc <- c("S3_1_met", mean(sig3_1_met), median(sig3_1_met))
med_container <- rbind(med_container, tc)
tc <- c("S3_1_cnv", mean(sig3_1_cnv), median(sig3_1_cnv))
med_container <- rbind(med_container, tc)
tc <- c("S3_1_som", mean(sig3_1_som), median(sig3_1_som))
med_container <- rbind(med_container, tc)

if(!is.null(sig3_2_met)){
 tc <- c("S3_2_met", mean(sig3_2_met), median(sig3_2_met))
 med_container <- rbind(med_container, tc)
}
tc <- c("S3_2_cnv", mean(sig3_2_cnv), median(sig3_2_cnv))
med_container <- rbind(med_container, tc)
tc <- c("S3_2_som", mean(sig3_2_som), median(sig3_2_som))
med_container <- rbind(med_container, tc)

tc <- c("S3_BRCA1&2_all", mean(sig3_germ_to_all), median(sig3_germ_to_all))
med_container <- rbind(med_container, tc)


if(!is.null(sig2_1_met)){
 tc <- c("S2_1_met", mean(sig2_1_met), median(sig2_1_met))
 med_container <- rbind(med_container, tc)
}
tc <- c("S2_1_cnv", mean(sig2_1_cnv), median(sig2_1_cnv))
med_container <- rbind(med_container, tc)
tc <- c("S2_1_som", mean(sig2_1_som), median(sig2_1_som))
med_container <- rbind(med_container, tc)

if(!is.null(sig2_2_met)){
 tc <- c("S2_2_met", mean(sig2_2_met), median(sig2_2_met))
 med_container <- rbind(med_container, tc)
}
if(!is.null(sig2_2_cnv)){
 tc <- c("S2_2_cnv", mean(sig2_2_cnv), median(sig2_2_cnv))
 med_container <- rbind(med_container, tc)
}
if(!is.null(sig2_2_som)){
 tc <- c("S2_2_som", mean(sig2_2_som), median(sig2_2_som))
 med_container <- rbind(med_container, tc)
}
if(!is.null(sig2_germ_to_all)){
tc <- c("S2_BRCA1&2_all", mean(sig2_germ_to_all), median(sig2_germ_to_all))
med_container <- rbind(med_container, tc)
}

tc <- c("Sig_all_BRCA1_met", mean(sigA_1_met), median(sigA_1_met))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA1_cnv", mean(sigA_1_cnv), median(sigA_1_cnv))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA1_som", mean(sigA_1_som), median(sigA_1_som))
med_container <- rbind(med_container, tc)

tc <- c("Sig_all_BRCA2_met", mean(sigA_2_met), median(sigA_2_met))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA2_cnv", mean(sigA_2_cnv), median(sigA_2_cnv))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA2_som", mean(sigA_2_som), median(sigA_2_som))
med_container <- rbind(med_container, tc)

tc <- c("Sig_all_BRCA1_1", mean(sigA_1_1), median(sigA_1_1))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA1_2", mean(sigA_1_2), median(sigA_1_2))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA2_2", mean(sigA_2_2), median(sigA_2_2))
med_container <- rbind(med_container, tc)

tc <- c("Sig_all_BRCA1&2_met", mean(sigA_combo_met), median(sigA_combo_met))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA1&2_cnv", mean(sigA_combo_cnv), median(sigA_combo_cnv))
med_container <- rbind(med_container, tc)
tc <- c("Sig_all_BRCA1&2_som", mean(sigA_combo_som), median(sigA_combo_som))
med_container <- rbind(med_container, tc)

tc <- c("S3_BRCA1&2_met", mean(sig3_combo_met), median(sig3_combo_met))
med_container <- rbind(med_container, tc)
tc <- c("S3_BRCA1&2_cnv", mean(sig3_combo_cnv), median(sig3_combo_cnv))
med_container <- rbind(med_container, tc)
tc <- c("S3_BRCA1&2_som", mean(sig3_combo_som), median(sig3_combo_som))
med_container <- rbind(med_container, tc)

tc <- c("Sig_all_BRCA1&2_all", mean(sigA_germ_to_all), median(sigA_germ_to_all))
med_container <- rbind(med_container, tc)
tc <- c("S3_BRCA1&2_all", mean(sig3_germ_to_all), median(sig3_germ_to_all))
med_container <- rbind(med_container, tc)
tc <- c("S2_BRCA1&2_all", mean(sig2_germ_to_all), median(sig2_germ_to_all))
med_container <- rbind(med_container, tc)

tc <- c("G_BRCA_BRCAlike", mean(sig_brca_like), median(sig_brca_like))
med_container <- rbind(med_container, tc)
tc <- c("G_BRCA_other", mean(sig_brca_other), median(sig_brca_other))
med_container <- rbind(med_container, tc)
tc <- c("G_BRCAlike_other", mean(sig_like_other), median(sig_like_other))
med_container <- rbind(med_container, tc)

head(med_container)
colnames(med_container) <- c("Data_ID", "Mean", "Median")
write.table(med_container, file="./Data/sig_3_2_med.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

set.seed(0)

print("Beginning run 1...")

#This code may look strange, but it should work for what it's supposed to do

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_sig3, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "LemonM1", "LemonD1", "S1")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig3_met_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig3_cnv_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig3_som_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_sig3, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA2_mutation", "LemonM2", "LemonD2", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig3_met_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig3_cnv_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig3_som_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_sig2, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA2_mutation", "LemonM2", "LemonD2", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig2_met_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig2_cnv_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig2_som_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_sig2, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "LemonM1", "LemonD1", "S1")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig2_met_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig2_cnv_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig2_som_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_euclid, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "LemonM1", "LemonD1", "S1")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_all_met_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_all_cnv_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig_all_som_medians_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_euclid, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA2_mutation", "LemonM2", "LemonD2", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_all_met_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_all_cnv_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig_all_som_medians_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)  

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test_3(iteration_c, rtsne_euclid, "B1A", "B2A", "B1A", "B2A", "G", "G", "G", "G")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_all_1_1.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_all_2_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig_all_1_2.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)  

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test_2(iteration_c, rtsne_euclid, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2", "D1", "D2", "S1", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_combo_met.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_combo_cnv.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig_combo_som.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test_2(iteration_c, rtsne_sig2, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2", "D1", "D2", "S1", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig2_combo_met.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig2_combo_cnv.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig2_combo_som.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test_2(iteration_c, rtsne_sig3, "BRCA_evidence", "Met", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "M1", "M2", "D1", "D2", "S1", "S2")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
colnames(stat_BRCA_som) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig3_combo_met.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig3_combo_cnv.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_som, file="./Data/Rando_sig3_combo_som.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

set.seed(4222)
stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_euclid, "BRCA_like", "BRCA_like", "BRCA_like", "BRCA_like", "BRCA", "BRCA_like", "Other", "lemon")
colnames(stat_BRCA_met) <- c("Mean", "Median")
colnames(stat_BRCA_cnv) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_BRCA_BRCAlike500.txt", append= TRUE, quote=FALSE, sep="\t", row.names=FALSE)
write.table(stat_BRCA_cnv, file="./Data/Rando_sig_BRCA_other500.txt", append= TRUE, quote=FALSE, sep="\t", row.names=FALSE)

stat_BRCA_met <- NULL
stat_BRCA_cnv <- NULL
stat_BRCA_som <- NULL
distribution_test(iteration_c, rtsne_euclid, "BRCA_like", "BRCA_like", "BRCA_like", "BRCA_like", "BRCA_like", "Other", "lemon", "lemon")
colnames(stat_BRCA_met) <- c("Mean", "Median")
write.table(stat_BRCA_met, file="./Data/Rando_sig_BRCAlike_other500.txt", append= TRUE, quote=FALSE, sep="\t", row.names=FALSE)

## "Lemon" used as a parameter will make it skip some analyses
distribution_test_2(iteration_c, rtsne_euclid, "BRCA_evidence", "Aberration", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2", "lemon", "lemon", "lemon", "lemon")
write.table(stat_BRCA_met, file="./Data/Rando_sig_combo_all.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

distribution_test_2(iteration_c, rtsne_sig2, "BRCA_evidence", "Aberration", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2", "lemon", "lemon", "lemon", "lemon")
write.table(stat_BRCA_met, file="./Data/Rando_sig2_combo_all.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)

distribution_test_2(iteration_c, rtsne_sig3, "BRCA_evidence", "Aberration", "CNV", "Som", "Germline_BRCA1_mutation", "Germline_BRCA2_mutation", "BRCA1", "BRCA2", "lemon", "lemon", "lemon", "lemon")
write.table(stat_BRCA_met, file="./Data/Rando_sig3_combo_all.txt", append= FALSE, quote=FALSE, sep="\t", row.names=FALSE)


